<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTyrxyzu\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTyrxyzu/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerTyrxyzu.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerTyrxyzu\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerTyrxyzu\appProdProjectContainer([
    'container.build_hash' => 'Tyrxyzu',
    'container.build_id' => 'e90033f3',
    'container.build_time' => 1607245947,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTyrxyzu');
